apiVersion: apps/v1
kind: Deployment
metadata:
  name: jfieuir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jfieuir
  template:
    metadata:
      labels:
        app: jfieuir
    spec:
      containers:
      - image: okteto.dev/jfieuir:latest
        name: jfieuir
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "5cbb7f1d-59e6-4fd5-9f70-17c59c749213"
        - name: Vless_Path
          value: "/5cbb7f1d-59e6-4fd5-9f70-17c59c749213"
        - name: Vmess_UUID
          value: "6ecd9299-530a-43d7-b714-63007273a31b"
        - name: Vmess_Path
          value: "/6ecd9299-530a-43d7-b714-63007273a31b"
        - name: Share_Path
          value: "/v2link"
